const eventsData = {
    bogota: [
        {
            id: 1,
            name: "Festival de Música Electrónica 2026",
            category: "musica",
            date: "15 Feb 2026",
            time: "20:00 - 04:00",
            location: "Parque Simón Bolívar, Bogotá",
            description: "Sumérgete en una noche de electrónica de clase mundial con DJs internacionales y nacionales. Experiencia visual con luces y proyecciones 3D.",
            price: 85000,
            image: "images/electronica.jpg",
            featured: true
        },
        {
            id: 2,
            name: "Exposición de Arte Contemporáneo",
            category: "cultura",
            date: "18 Feb 2026",
            time: "10:00 - 18:00",
            location: "Museo de Arte Moderno, Bogotá",
            description: "Obras maestras de artistas colombianos e internacionales. Recorridos guiados disponibles.",
            price: 25000,
            image: "images/arte_contemporaneo.jpg",
            featured: false
        },
        {
            id: 3,
            name: "Festival Gastronómico Bogotá 2026",
            category: "gastronomia",
            date: "22 Feb 2026",
            time: "12:00 - 22:00",
            location: "Plaza Mayor, Centro Bogotá",
            description: "Más de 50 restaurantes showcaseando lo mejor de la cocina colombiana e internacional.",
            price: 45000,
            image: "images/gastronomia.jpg",
            featured: true
        },
        {
            id: 4,
            name: "Concierto Orquesta Sinfónica Nacional",
            category: "musica",
            date: "25 Feb 2026",
            time: "19:30 - 21:30",
            location: "Teatro Colón, Bogotá",
            description: "Clásicos inmortales con la prestigiosa Orquesta Sinfónica Nacional bajo la dirección de un maestro internacional.",
            price: 95000,
            image: "images/orquesta.jpg",
            featured: false
        },
        {
            id: 5,
            name: "Conferencia Tecnología e Innovación",
            category: "tecnologia",
            date: "28 Feb 2026",
            time: "08:00 - 17:00",
            location: "Centro de Convenciones Ágora, Bogotá",
            description: "Keynotes de líderes tech, workshops prácticos y networking con emprendedores colombianos.",
            price: 150000,
            image: "images/tecnologia.jpg",
            featured: true
        },
        {
            id: 6,
            name: "Partido Fútbol Profesional: Millonarios vs Atlético Nacional",
            category: "deportes",
            date: "02 Mar 2026",
            time: "15:30 - 17:30",
            location: "Estadio Nemesio Camacho El Campín, Bogotá",
            description: "Clásico del fútbol colombiano. Ambiente electrizante garantizado en el corazón de Bogotá.",
            price: 75000,
            image: "images/futbol.jpg",
            featured: false
        },
        {
            id: 7,
            name: "Taller de Fotografía Profesional",
            category: "cultura",
            date: "05 Mar 2026",
            time: "14:00 - 18:00",
            location: "Centro Cultural Gabriel García Márquez, Bogotá",
            description: "Aprende técnicas de fotografía profesional con un fotógrafo galardonado. Incluye salida fotográfica.",
            price: 120000,
            image: "images/fotografia.jpg",
            featured: false
        }
    ],
    medellin: [
        {
            id: 101,
            name: "Feria de las Flores Medellín",
            category: "cultura",
            date: "01 Ago 2026",
            time: "09:00 - 22:00",
            location: "Parque Arvi, Medellín",
            description: "La más colorida y tradicional fiesta de Medellín. Desfiles con flores, conciertos en vivo y celebración de la cultura paisa.",
            price: 35000,
            image: "images/feria_flores.jpg",
            featured: true
        },
        {
            id: 102,
            name: "Concierto Reggaeton Live",
            category: "musica",
            date: "20 Feb 2026",
            time: "21:00 - 02:00",
            location: "Atanasio Girardot, Medellín",
            description: "Principales exponentes del reggaeton latino en un escenario de luces y efectos especiales.",
            price: 65000,
            image: "images/reggaeton.jpg",
            featured: true
        },
        {
            id: 103,
            name: "Encuentro Empresarial Valle de Aburrá",
            category: "negocios",
            date: "23 Feb 2026",
            time: "08:30 - 16:00",
            location: "Corferias Centro de Convenciones, Medellín",
            description: "Networking de alto nivel con empresarios, inversores y emprendedores de Colombia y el exterior.",
            price: 180000,
            image: "images/negocios.jpg",
            featured: false
        },
        {
            id: 104,
            name: "Festival de Comida Callejera",
            category: "gastronomia",
            date: "01 Mar 2026",
            time: "11:00 - 20:00",
            location: "Parque Bolívar, Medellín",
            description: "Sabores auténticos de la cocina paisa y platillos internacionales en un ambiente festivo.",
            price: 40000,
            image: "images/gastronomia.jpg",
            featured: false
        },
        {
            id: 105,
            name: "Carrera Atletismo Media Maratón Medellín",
            category: "deportes",
            date: "09 Mar 2026",
            time: "06:30 - 10:00",
            location: "Centro Administrativo Medellín, Medellín",
            description: "21 km de recorrido por las principales avenidas de Medellín. Participación de atletas nacionales e internacionales.",
            price: 55000,
            image: "images/atletismo.jpg",
            featured: false
        },
        {
            id: 106,
            name: "Exposición Museo de Antioquia",
            category: "cultura",
            date: "15 Mar 2026",
            time: "10:00 - 17:00",
            location: "Museo de Antioquia, Medellín",
            description: "Galería permanente de Botero y exposiciones temporales de arte contemporáneo y prehispánico.",
            price: 28000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 107,
            name: "Hackathon Innovación Digital Medellín",
            category: "tecnologia",
            date: "24 Feb 2026",
            time: "09:00 - 20:00",
            location: "Centro de Innovación EAFIT, Medellín",
            description: "Compite con equipos multidisciplinarios para resolver desafíos reales de empresas colombianas.",
            price: 0,
            image: "images/tecnologia.jpg",
            featured: false
        }
    ],
    cali: [
        {
            id: 201,
            name: "Festival Salsa World Cali 2026",
            category: "musica",
            date: "03 Mar 2026",
            time: "20:00 - 05:00",
            location: "Anfiteatro La Caña, Cali",
            description: "La capital mundial de la salsa celebra con orquestas legendarias, bailarines profesionales y mucha sabor caleño.",
            price: 55000,
            image: "images/salsa.jpg",
            featured: true
        },
        {
            id: 202,
            name: "Campeonato Nacional de Salsa",
            category: "deportes",
            date: "04 Mar 2026",
            time: "19:00 - 23:00",
            location: "Teatroclub, Cali",
            description: "Parejas de bailarines colombianos compitiendo por el título nacional. Ambiente de pura energía.",
            price: 45000,
            image: "images/campeonato.jpg",
            featured: true
        },
        {
            id: 203,
            name: "Feria Gastronómica Vallecaucana",
            category: "gastronomia",
            date: "08 Mar 2026",
            time: "12:00 - 21:00",
            location: "Centro Comercial Chipichape, Cali",
            description: "Delicias de la región: sancocho, ajiaco, empanadas y postres tradicionales. Degustación libre.",
            price: 60000,
            image: "images/gastronomia.jpg",
            featured: false
        },
        {
            id: 204,
            name: "Concierto Artista Reggaeton Urbano",
            category: "musica",
            date: "12 Mar 2026",
            time: "21:00 - 01:00",
            location: "Coliseo Pascual Guerrero, Cali",
            description: "Artista international en concierto único en Cali con invitados sorpresa.",
            price: 85000,
            image: "images/reggaeton.jpg",
            featured: false
        },
        {
            id: 205,
            name: "Clase Magistral de Salsa",
            category: "cultura",
            date: "15 Mar 2026",
            time: "18:00 - 20:00",
            location: "Academia de Danza Cali, Cali",
            description: "Aprende directamente de maestros de salsa caleña. Abierto para todos los niveles.",
            price: 35000,
            image: "images/salsa.jpg",
            featured: false
        },
        {
            id: 206,
            name: "Exposición Museo Arqueológico",
            category: "cultura",
            date: "20 Mar 2026",
            time: "10:00 - 17:00",
            location: "Museo Arqueológico, Cali",
            description: "Artefactos precolombinos, piezas de oro y tesoros de las culturas del Pacífico colombiano.",
            price: 20000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 207,
            name: "Torneo Fútbol Sala Profesional",
            category: "deportes",
            date: "25 Mar 2026",
            time: "14:00 - 19:00",
            location: "Coliseo Eléctrico, Cali",
            description: "Equipos de fútbol sala de toda Colombia compitiendo en un ambiente lleno de emoción.",
            price: 30000,
            image: "images/futbol.jpg",
            featured: false
        }
    ],
    barranquilla: [
        {
            id: 301,
            name: "Carnaval de Barranquilla 2026",
            category: "cultura",
            date: "01 Mar 2026",
            time: "09:00 - 23:00",
            location: "Centro Histórico de Barranquilla",
            description: "Una de las festividades más importantes de Colombia. Desfiles, cumbia, gaita y celebración de la cultura caribeña.",
            price: 50000,
            image: "images/carnaval.jpg",
            featured: true
        },
        {
            id: 302,
            name: "Concierto Vallenato en Vivo",
            category: "musica",
            date: "15 Feb 2026",
            time: "19:00 - 23:00",
            location: "Teatro Amira de la Rosa, Barranquilla",
            description: "Leyendas del vallenato en un concierto memorable. Pura nostalgia y tradición costeña.",
            price: 65000,
            image: "images/vallenato.jpg",
            featured: false
        },
        {
            id: 303,
            name: "Festival de Pescado Frito",
            category: "gastronomia",
            date: "20 Feb 2026",
            time: "11:00 - 20:00",
            location: "Playa de Puerto Colombia, Barranquilla",
            description: "Mariscos, pescados frescos y bebidas refrescantes en ambiente playero. Música de banda en vivo.",
            price: 45000,
            image: "images/pescado.jpg",
            featured: true
        },
        {
            id: 304,
            name: "Encuentro de Empresarios Caribeños",
            category: "negocios",
            date: "25 Feb 2026",
            time: "08:00 - 15:00",
            location: "Hotel Hilton Barranquilla, Barranquilla",
            description: "Oportunidades de negocios en turismo, comercio y emprendimiento en la costa caribeña.",
            price: 160000,
            image: "images/negocios.jpg",
            featured: false
        },
        {
            id: 305,
            name: "Carrera de Atletismo Playa",
            category: "deportes",
            date: "01 Mar 2026",
            time: "06:00 - 09:00",
            location: "Playa de Barranquilla, Barranquilla",
            description: "10 km corriendo en la arena de la playa. Desayuno incluido al finalizar.",
            price: 40000,
            image: "images/atletismo.jpg",
            featured: false
        },
        {
            id: 306,
            name: "Taller de Artesanía Caribeña",
            category: "cultura",
            date: "05 Mar 2026",
            time: "14:00 - 17:00",
            location: "Centro Cultural Caribe, Barranquilla",
            description: "Aprende a hacer mochilas wayuu, sombreros vueltiao y otras artesanías típicas de la región.",
            price: 60000,
            image: "images/artesanía.jpg",
            featured: false
        },
        {
            id: 307,
            name: "Festival de Tecnología Caribeña",
            category: "tecnologia",
            date: "10 Mar 2026",
            time: "09:00 - 17:00",
            location: "UNINORTE Campus, Barranquilla",
            description: "Innovadores, startups y empresas tech mostrando soluciones para la región caribeña.",
            price: 120000,
            image: "images/tecnologia.jpg",
            featured: false
        }
    ],
    cartagena: [
        {
            id: 401,
            name: "Festival de Cine Cartagena de Indias",
            category: "cultura",
            date: "20 Feb 2026",
            time: "10:00 - 22:00",
            location: "Teatro Heredia, Cartagena",
            description: "Proyección de películas internacionales y nacionales en la mágica ciudad amurallada. Charlas con cineastas.",
            price: 40000,
            image: "images/cine.jpg",
            featured: true
        },
        {
            id: 402,
            name: "Concierto Música Tropical Caribeña",
            category: "musica",
            date: "25 Feb 2026",
            time: "20:00 - 23:00",
            location: "Centro de Convenciones, Cartagena",
            description: "Orquestas de música tropical, champeta y ritmos caribeños en vivo.",
            price: 75000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 403,
            name: "Tour Gastronómico por Cartagena Vieja",
            category: "gastronomia",
            date: "01 Mar 2026",
            time: "12:00 - 18:00",
            location: "Barrio Getsemaní, Cartagena",
            description: "Recorrido por restaurantes históricos probando especialidades de la costa. Guía turístico incluido.",
            price: 165000,
            image: "images/gastronomia.jpg",
            featured: true
        },
        {
            id: 404,
            name: "Festival de Arte Urbano",
            category: "cultura",
            date: "08 Mar 2026",
            time: "09:00 - 18:00",
            location: "Getsemaní, Cartagena",
            description: "Muralistas nacionales e internacionales creando arte en vivo. Talleres y competencias.",
            price: 25000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 405,
            name: "Torneo de Vóley Playa Cartagena",
            category: "deportes",
            date: "15 Mar 2026",
            time: "10:00 - 17:00",
            location: "Playa Bocagrande, Cartagena",
            description: "Equipos profesionales de voleibol compitiendo en la hermosa playa de Cartagena.",
            price: 35000,
            image: "images/voley.jpg",
            featured: false
        },
        {
            id: 406,
            name: "Conferencia Turismo Sostenible",
            category: "negocios",
            date: "20 Mar 2026",
            time: "08:30 - 16:00",
            location: "Hotel Sofitel Santa Clara, Cartagena",
            description: "Expertos en turismo hablando sobre desarrollo sostenible en destinos caribeños.",
            price: 140000,
            image: "images/turismo.jpg",
            featured: false
        },
        {
            id: 407,
            name: "Clase de Buceo y Snorkel",
            category: "deportes",
            date: "22 Mar 2026",
            time: "06:00 - 12:00",
            location: "Playa Rosario, Cartagena",
            description: "Instructores certificados llevándote a explorar los arrecifes de coral y fauna marina.",
            price: 180000,
            image: "images/buceo.jpg",
            featured: false
        }
    ],
    bucaramanga: [
        {
            id: 501,
            name: "Festival de Música Independiente Bucaramanga",
            category: "musica",
            date: "10 Feb 2026",
            time: "19:00 - 01:00",
            location: "Parque García Rovira, Bucaramanga",
            description: "Bandas locales e internacionales de música indie. Ambiente festivo y artístico.",
            price: 45000,
            image: "images/música.jpg",
            featured: true
        },
        {
            id: 502,
            name: "Exposición Pintura Moderna",
            category: "cultura",
            date: "15 Feb 2026",
            time: "10:00 - 18:00",
            location: "Galería de Arte Metropolitana, Bucaramanga",
            description: "Artistas santandereanos y nacionales mostrando obras de pintura contemporánea.",
            price: 18000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 503,
            name: "Festival de Hormigas Culonas",
            category: "gastronomia",
            date: "20 Feb 2026",
            time: "11:00 - 19:00",
            location: "Centro Comercial Mayales, Bucaramanga",
            description: "Especialidad santandereana: degustación de hormigas culonas fritas, ajiaco, morcilla y más.",
            price: 50000,
            image: "images/gastronomia.jpg",
            featured: true
        },
        {
            id: 504,
            name: "Encuentro de Emprendedores Tech",
            category: "tecnologia",
            date: "25 Feb 2026",
            time: "08:00 - 17:00",
            location: "Incubadora Empresarial UIS, Bucaramanga",
            description: "Startups de Santander presentando ideas innovadoras. Oportunidades de inversión.",
            price: 100000,
            image: "images/tecnologia.jpg",
            featured: false
        },
        {
            id: 505,
            name: "Maratón Cicletero Bucaramanga",
            category: "deportes",
            date: "01 Mar 2026",
            time: "06:00 - 11:00",
            location: "Centro Histórico, Bucaramanga",
            description: "40 km en bicicleta por senderos seguros. Apto para todos los niveles.",
            price: 35000,
            image: "images/atletismo.jpg",
            featured: false
        },
        {
            id: 506,
            name: "Taller de Fotografía de Naturaleza",
            category: "cultura",
            date: "08 Mar 2026",
            time: "08:00 - 12:00",
            location: "Girón, Bucaramanga",
            description: "Captura la belleza de los paisajes santandereanos. Salida fotográfica incluida.",
            price: 85000,
            image: "images/fotografia.jpg",
            featured: false
        },
        {
            id: 507,
            name: "Competencia de Parapente",
            category: "deportes",
            date: "15 Mar 2026",
            time: "08:00 - 16:00",
            location: "Cerro de la Paz, Bucaramanga",
            description: "Parapentistas de Colombia volando en las térmicas de Bucaramanga. Espectáculo aéreo.",
            price: 40000,
            image: "images/parapente.jpg",
            featured: false
        }
    ],
    cucuta: [
        {
            id: 601,
            name: "Festival de Música Latinoamericana",
            category: "musica",
            date: "12 Feb 2026",
            time: "19:00 - 23:00",
            location: "Teatro Municipal, Cúcuta",
            description: "Artistas de Colombia, Venezuela y otros países latinoamericanos en un mega evento musical.",
            price: 55000,
            image: "images/música.jpg",
            featured: true
        },
        {
            id: 602,
            name: "Feria Fronteriza de Emprendimiento",
            category: "negocios",
            date: "18 Feb 2026",
            time: "09:00 - 17:00",
            location: "Centro de Convenciones, Cúcuta",
            description: "Empresarios de ambos lados de la frontera compartiendo oportunidades comerciales.",
            price: 120000,
            image: "images/negocios.jpg",
            featured: false
        },
        {
            id: 603,
            name: "Encuentro Gastronómico Fronterizo",
            category: "gastronomia",
            date: "22 Feb 2026",
            time: "12:00 - 20:00",
            location: "Parque Santander, Cúcuta",
            description: "Sabores de ambas fronteras: comida colombiana y llanera. Bebidas regionales incluidas.",
            price: 40000,
            image: "images/gastronomia.jpg",
            featured: true
        },
        {
            id: 604,
            name: "Concierto Música Llanera",
            category: "musica",
            date: "01 Mar 2026",
            time: "18:00 - 22:00",
            location: "Auditorio de Cúcuta, Cúcuta",
            description: "Arpistas, llaneros y trovadores tocando música de los Llanos Orientales.",
            price: 45000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 605,
            name: "Carrera Atlética Fronteriza",
            category: "deportes",
            date: "08 Mar 2026",
            time: "06:00 - 09:00",
            location: "Puente Internacional Simón Bolívar, Cúcuta",
            description: "Media maratón internacional en la frontera con Venezuela.",
            price: 30000,
            image: "images/atletismo.jpg",
            featured: false
        },
        {
            id: 606,
            name: "Taller de Artesanías Llaneras",
            category: "cultura",
            date: "10 Mar 2026",
            time: "14:00 - 17:00",
            location: "Casa de la Cultura, Cúcuta",
            description: "Aprende a hacer mochilas, sombreros y tejidos característicos de la región llanera.",
            price: 50000,
            image: "images/artesanía.jpg",
            featured: false
        },
        {
            id: 607,
            name: "Festival de Tecnología Digital Fronterizo",
            category: "tecnologia",
            date: "15 Mar 2026",
            time: "08:00 - 16:00",
            location: "Universidad de Pamplona, Cúcuta",
            description: "Soluciones tecnológicas para integración comercial fronteriza.",
            price: 100000,
            image: "images/tecnologia.jpg",
            featured: false
        }
    ],
    "santa-marta": [
        {
            id: 701,
            name: "Festival de Música de Playa",
            category: "musica",
            date: "14 Feb 2026",
            time: "18:00 - 23:00",
            location: "Playa de Santa Marta, Santa Marta",
            description: "Artistas nacionales tocando música tropical, reggae y música de playa en arena blanca.",
            price: 50000,
            image: "images/música.jpg",
            featured: true
        },
        {
            id: 702,
            name: "Tour Ciudad Perdida",
            category: "cultura",
            date: "20 Feb 2026",
            time: "06:00 - 18:00",
            location: "Inicio Ruta Ciudad Perdida, Santa Marta",
            description: "Trekking de 4 días hacia la Ciudad Perdida. Campamento, comidas y guías incluidos.",
            price: 450000,
            image: "images/tour.jpg",
            featured: false
        },
        {
            id: 703,
            name: "Festival del Camarón",
            category: "gastronomia",
            date: "25 Feb 2026",
            time: "11:00 - 20:00",
            location: "Mercado Público, Santa Marta",
            description: "Camarones frescos preparados de todas las formas: al ajillo, a la criolla, en pasta.",
            price: 65000,
            image: "images/gastronomia.jpg",
            featured: true
        },
        {
            id: 704,
            name: "Exposición Arqueología Tayrona",
            category: "cultura",
            date: "01 Mar 2026",
            time: "09:00 - 17:00",
            location: "Museo Arqueológico, Santa Marta",
            description: "Artefactos de la civilización Tayrona y piezas del Parque Nacional Natural.",
            price: 22000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 705,
            name: "Competencia de Buceo y Fotosub",
            category: "deportes",
            date: "08 Mar 2026",
            time: "08:00 - 16:00",
            location: "Playas de Santa Marta, Santa Marta",
            description: "Buzos profesionales fotografiando la fauna marina. Premios para las mejores fotos.",
            price: 90000,
            image: "images/buceo.jpg",
            featured: false
        },
        {
            id: 706,
            name: "Clase de Yoga y Meditación Playa",
            category: "cultura",
            date: "12 Mar 2026",
            time: "06:00 - 08:00",
            location: "Playa Gaira, Santa Marta",
            description: "Sesión de yoga al amanecer frente al mar Caribe con instructor certificado.",
            price: 35000,
            image: "images/yoga.jpg",
            featured: false
        },
        {
            id: 707,
            name: "Conferencia Ecoturismo Sostenible",
            category: "negocios",
            date: "18 Mar 2026",
            time: "09:00 - 15:00",
            location: "Hotel Irotama, Santa Marta",
            description: "Emprendedores del turismo compartiendo modelos de negocios sostenibles en la Sierra Nevada.",
            price: 130000,
            image: "images/turismo.jpg",
            featured: false
        }
    ],
    pereira: [
        {
            id: 801,
            name: "Festival del Café Pereira",
            category: "gastronomia",
            date: "10 Feb 2026",
            time: "09:00 - 18:00",
            location: "Parque Agroecológico, Pereira",
            description: "Cataciones de café, tienda de café gourmet, charlas sobre cultivo de café de altura.",
            price: 45000,
            image: "images/café.jpg",
            featured: true
        },
        {
            id: 802,
            name: "Concierto de Música Folclórica",
            category: "musica",
            date: "16 Feb 2026",
            time: "19:00 - 22:00",
            location: "Teatro Santiago Londoño, Pereira",
            description: "Música de la región cafetera: bandas, orquestas y artistas locales.",
            price: 40000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 803,
            name: "Encuentro de Cafeteros de Colombia",
            category: "negocios",
            date: "20 Feb 2026",
            time: "08:00 - 17:00",
            location: "Federación de Cafeteros, Pereira",
            description: "Reunión de productores de café, exportadores e inversionistas. Degustaciones incluidas.",
            price: 150000,
            image: "images/negocios.jpg",
            featured: true
        },
        {
            id: 804,
            name: "Taller Procesamiento Artesanal del Café",
            category: "cultura",
            date: "25 Feb 2026",
            time: "14:00 - 17:00",
            location: "Finca Agroecológica, Pereira",
            description: "Aprende a procesar café desde el grano hasta la taza perfecta.",
            price: 95000,
            image: "images/café.jpg",
            featured: false
        },
        {
            id: 805,
            name: "Maratón de Montaña Pereira",
            category: "deportes",
            date: "01 Mar 2026",
            time: "06:00 - 12:00",
            location: "Cercanías de Pereira, Pereira",
            description: "Recorrido de trail running por las montañas de la región cafetera.",
            price: 50000,
            image: "images/atletismo.jpg",
            featured: false
        },
        {
            id: 806,
            name: "Exposición de Arte Contemporáneo",
            category: "cultura",
            date: "08 Mar 2026",
            time: "10:00 - 18:00",
            location: "Museo de Arte, Pereira",
            description: "Obras de artistas del Eje Cafetero y artistas internacionales.",
            price: 25000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 807,
            name: "Festival de Innovación Agrícola",
            category: "tecnologia",
            date: "15 Mar 2026",
            time: "09:00 - 17:00",
            location: "Universidad Tecnológica de Pereira, Pereira",
            description: "Tecnología y innovación aplicada a la agricultura y producción cafetera.",
            price: 0,
            image: "images/tecnologia.jpg",
            featured: false
        }
    ],
    manizales: [
        {
            id: 901,
            name: "Festival Folclórico Manizales",
            category: "cultura",
            date: "08 Jan 2026",
            time: "09:00 - 22:00",
            location: "Centro de Manizales, Manizales",
            description: "Desfiles, música folclórica, danzas típicas de la región cafetera. Evento tradicional y colorido.",
            price: 40000,
            image: "images/cultura.jpg",
            featured: true
        },
        {
            id: 902,
            name: "Concierto Sinfónico Manizales",
            category: "musica",
            date: "20 Feb 2026",
            time: "19:30 - 21:00",
            location: "Palacio de Artes, Manizales",
            description: "Orquesta Sinfónica de Caldas interpretando clásicos de la música universal.",
            price: 55000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 903,
            name: "Tour Cafetería y Gastronómico",
            category: "gastronomia",
            date: "23 Feb 2026",
            time: "10:00 - 16:00",
            location: "Zona Cafetera, Manizales",
            description: "Visita a cafeterías, degustación de café y comidas típicas. Transporte incluido.",
            price: 120000,
            image: "images/café.jpg",
            featured: true
        },
        {
            id: 904,
            name: "Encuentro de Actores Culturales",
            category: "cultura",
            date: "01 Mar 2026",
            time: "10:00 - 17:00",
            location: "Teatro de Manizales, Manizales",
            description: "Coloquio sobre producción cultural, financiamiento y gestión de proyectos artísticos.",
            price: 60000,
            image: "images/cultura.jpg",
            featured: false
        },
        {
            id: 905,
            name: "Ascenso al Nevado del Ruiz",
            category: "deportes",
            date: "07 Mar 2026",
            time: "04:00 - 16:00",
            location: "Parque Natural Nevado del Ruiz, Manizales",
            description: "Escalada guiada al volcán nevado. Experiencia de alta montaña.",
            price: 280000,
            image: "images/montaña.jpg",
            featured: false
        },
        {
            id: 906,
            name: "Exposición Museos Manizales",
            category: "cultura",
            date: "15 Mar 2026",
            time: "10:00 - 17:00",
            location: "Museo Arqueológico, Manizales",
            description: "Colecciones de arte precolombino y contemporáneo de la región.",
            price: 20000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 907,
            name: "Foro de Emprendimiento Rural",
            category: "negocios",
            date: "20 Mar 2026",
            time: "08:00 - 16:00",
            location: "Centro de Convenciones, Manizales",
            description: "Proyectos emprendedores de la zona rural, agroturismo, café de especialidad.",
            price: 140000,
            image: "images/negocios.jpg",
            featured: false
        }
    ],
    villavicencio: [
        {
            id: 1001,
            name: "Festival Llanero Villavicencio",
            category: "cultura",
            date: "28 Nov 2025",
            time: "09:00 - 23:00",
            location: "Centro de Villavicencio, Villavicencio",
            description: "Celebración de la cultura llanera: música, danza, gastronomía y tradiciones del Llano Oriental.",
            price: 45000,
            image: "images/cultura.jpg",
            featured: true
        },
        {
            id: 1002,
            name: "Concierto Música Llanera en Vivo",
            category: "musica",
            date: "18 Feb 2026",
            time: "20:00 - 23:00",
            location: "Teatro Lido, Villavicencio",
            description: "Artistas destacados del joropo y música llanera en concierto único.",
            price: 50000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 1003,
            name: "Festival Gastronómico Llanero",
            category: "gastronomia",
            date: "22 Feb 2026",
            time: "11:00 - 21:00",
            location: "Parque Llanos del Yari, Villavicencio",
            description: "Carne asada a la llanera, arepa con queso, miel de panela. Ambiente festivo.",
            price: 55000,
            image: "images/gastronomia.jpg",
            featured: true
        },
        {
            id: 1004,
            name: "Tour Ecológico Ariari",
            category: "cultura",
            date: "01 Mar 2026",
            time: "06:00 - 18:00",
            location: "Río Ariari, Villavicencio",
            description: "Recorrido por la naturaleza del Meta: avistamiento de fauna, flora llanera.",
            price: 130000,
            image: "images/naturaleza.jpg",
            featured: false
        },
        {
            id: 1005,
            name: "Competencia de Caballos Llaneros",
            category: "deportes",
            date: "08 Mar 2026",
            time: "10:00 - 17:00",
            location: "Coliseo Cubierto, Villavicencio",
            description: "Competencia ecuestre con razas llaneras. Exhibiciones de jinetes profesionales.",
            price: 35000,
            image: "images/caballos.jpg",
            featured: false
        },
        {
            id: 1006,
            name: "Taller de Ordeño Tradicional",
            category: "cultura",
            date: "12 Mar 2026",
            time: "14:00 - 17:00",
            location: "Finca Agroecológica, Villavicencio",
            description: "Aprende técnicas tradicionales de ordeño y producción de quesos llaneros.",
            price: 65000,
            image: "images/queso.jpg",
            featured: false
        },
        {
            id: 1007,
            name: "Encuentro de Ganaderos",
            category: "negocios",
            date: "18 Mar 2026",
            time: "08:30 - 16:00",
            location: "Gremio de Ganaderos, Villavicencio",
            description: "Reunión de productores ganaderos, proveedores y comercializadores del Meta.",
            price: 120000,
            image: "images/negocios.jpg",
            featured: false
        }
    ],
    ibage: [
        {
            id: 1101,
            name: "Festival Folclórico Ibagué",
            category: "cultura",
            date: "20 Jun 2026",
            time: "09:00 - 23:00",
            location: "Centro Histórico Ibagué, Ibagué",
            description: "La capital musical de Colombia. Música, danzas, desfiles y celebración de la tradición tolimense.",
            price: 35000,
            image: "images/música.jpg",
            featured: true
        },
        {
            id: 1102,
            name: "Concierto Orquesta Sinfónica Tolima",
            category: "musica",
            date: "17 Feb 2026",
            time: "19:00 - 21:00",
            location: "Conservatorio del Tolima, Ibagué",
            description: "La Orquesta Sinfónica interpretando clásicos y composiciones contemporáneas.",
            price: 40000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 1103,
            name: "Festival Gastronómico Tolimense",
            category: "gastronomia",
            date: "24 Feb 2026",
            time: "12:00 - 20:00",
            location: "Centro Comercial Ibagué, Ibagué",
            description: "Tamales tolimenses, ajiaco, empanadas y postres típicos de la región.",
            price: 48000,
            image: "images/gastronomia.jpg",
            featured: true
        },
        {
            id: 1104,
            name: "Tour Guaitarilla y Naturaleza",
            category: "cultura",
            date: "28 Feb 2026",
            time: "08:00 - 16:00",
            location: "Guaitarilla Ibagué, Ibagué",
            description: "Visita a jardines, cascadas y reservas naturales del Tolima.",
            price: 85000,
            image: "images/naturaleza.jpg",
            featured: false
        },
        {
            id: 1105,
            name: "Maratón de Montaña Ibagué",
            category: "deportes",
            date: "07 Mar 2026",
            time: "06:00 - 11:00",
            location: "Alrededores de Ibagué, Ibagué",
            description: "Trail running por paisajes de la región. Apto para todos los niveles.",
            price: 40000,
            image: "images/atletismo.jpg",
            featured: false
        },
        {
            id: 1106,
            name: "Exposición Música y Arte Tolimense",
            category: "cultura",
            date: "14 Mar 2026",
            time: "10:00 - 17:00",
            location: "Museo de la Música, Ibagué",
            description: "Instrumentos históricos, partituras y arte de la capital musical colombiana.",
            price: 22000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 1107,
            name: "Conferencia Turismo Cultural Tolima",
            category: "negocios",
            date: "19 Mar 2026",
            time: "08:00 - 15:00",
            location: "Cámara de Comercio, Ibagué",
            description: "Oportunidades de turismo cultural, emprendimiento y desarrollo en el Tolima.",
            price: 110000,
            image: "images/turismo.jpg",
            featured: false
        }
    ],
    neiva: [
        {
            id: 1201,
            name: "Festival de Bambuco Neiva",
            category: "musica",
            date: "24 Jun 2026",
            time: "09:00 - 23:00",
            location: "Centro Cívico Neiva, Neiva",
            description: "Celebración del bambuco huilense. Música, danza, gastronomía y tradición cultural.",
            price: 40000,
            image: "images/música.jpg",
            featured: true
        },
        {
            id: 1202,
            name: "Concierto Gaita y Folclore",
            category: "musica",
            date: "19 Feb 2026",
            time: "19:00 - 22:00",
            location: "Teatro Eustaquio García, Neiva",
            description: "Artistas interpretan música de gaita y folclore del Huila.",
            price: 38000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 1203,
            name: "Festival Gastronómico Huilense",
            category: "gastronomia",
            date: "23 Feb 2026",
            time: "11:00 - 19:00",
            location: "Parque Bolívar, Neiva",
            description: "Comidas huilenses: ajiaco, empanadas, fritanga y bebidas regionales.",
            price: 45000,
            image: "images/gastronomia.jpg",
            featured: true
        },
        {
            id: 1204,
            name: "Tour Arqueológico San Agustín",
            category: "cultura",
            date: "02 Mar 2026",
            time: "06:00 - 18:00",
            location: "San Agustín, Neiva",
            description: "Excursión a el sitio arqueológico de San Agustín. Estatuas precolombinas y tumbas ancestrales.",
            price: 150000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 1205,
            name: "Competencia de Rafting en el Río Magdalena",
            category: "deportes",
            date: "09 Mar 2026",
            time: "06:00 - 14:00",
            location: "Río Magdalena, Neiva",
            description: "Aventura en aguas bravas del río. Guías especializados y equipo completo.",
            price: 95000,
            image: "images/rafting.jpg",
            featured: false
        },
        {
            id: 1206,
            name: "Exposición Arte Precolombino",
            category: "cultura",
            date: "16 Mar 2026",
            time: "10:00 - 17:00",
            location: "Museo Arqueológico, Neiva",
            description: "Piezas de cerámica, arte y artefactos de culturas ancestrales del Huila.",
            price: 25000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 1207,
            name: "Foro de Desarrollo Rural y Agrícola",
            category: "negocios",
            date: "21 Mar 2026",
            time: "08:00 - 16:00",
            location: "Centro de Convenciones, Neiva",
            description: "Emprendimiento agrícola, café de altura y proyectos sostenibles en el Huila.",
            price: 130000,
            image: "images/negocios.jpg",
            featured: false
        }
    ],
    pasto: [
        {
            id: 1301,
            name: "Carnaval de Negros y Blancos Pasto",
            category: "cultura",
            date: "02 Jan 2026",
            time: "09:00 - 22:00",
            location: "Centro de Pasto, Pasto",
            description: "Uno de los carnavales más antiguos de América. Desfiles, pinturas y colorido nariñense.",
            price: 50000,
            image: "images/carnaval.jpg",
            featured: true
        },
        {
            id: 1302,
            name: "Concierto Música Nariñense",
            category: "musica",
            date: "21 Feb 2026",
            time: "19:00 - 22:00",
            location: "Teatro Imperial, Pasto",
            description: "Bandas sinfónicas y artistas de la región tocando música nariñense tradicional.",
            price: 42000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 1303,
            name: "Taller Artesanía Nariñense",
            category: "cultura",
            date: "26 Feb 2026",
            time: "14:00 - 17:00",
            location: "Casa de la Cultura, Pasto",
            description: "Aprende técnicas de barniz de Pasto, mochilas wayuu y artesanía regional.",
            price: 70000,
            image: "images/artesanía.jpg",
            featured: false
        },
        {
            id: 1304,
            name: "Festival Gastronómico Nariñense",
            category: "gastronomia",
            date: "03 Mar 2026",
            time: "11:00 - 20:00",
            location: "Centro Comercial Pasto, Pasto",
            description: "Comidas típicas: caldo de papa, ajiaco, empanadas y carne con papas nativas.",
            price: 50000,
            image: "images/gastronomia.jpg",
            featured: true
        },
        {
            id: 1305,
            name: "Trekking Laguna de la Cocha",
            category: "deportes",
            date: "10 Mar 2026",
            time: "06:00 - 15:00",
            location: "Laguna de la Cocha, Pasto",
            description: "Caminata ecológica a una de las lagunas más hermosas de Colombia.",
            price: 110000,
            image: "images/naturaleza.jpg",
            featured: false
        },
        {
            id: 1306,
            name: "Exposición Museo San Juan Bautista",
            category: "cultura",
            date: "17 Mar 2026",
            time: "10:00 - 17:00",
            location: "Museo San Juan Bautista, Pasto",
            description: "Arte religioso, arte contemporáneo y colecciones de la región nariñense.",
            price: 20000,
            image: "images/arte.jpg",
            featured: false
        },
        {
            id: 1307,
            name: "Conferencia Turismo y Emprendimiento Nariña",
            category: "negocios",
            date: "22 Mar 2026",
            time: "08:30 - 16:00",
            location: "Cámara de Comercio, Pasto",
            description: "Oportunidades de turismo comunitario, agroturismo y emprendimiento en Nariño.",
            price: 125000,
            image: "images/negocios.jpg",
            featured: false
        }
    ],
    armenia: [
        {
            id: 1401,
            name: "Festival del Café Armenia",
            category: "gastronomia",
            date: "12 Feb 2026",
            time: "09:00 - 18:00",
            location: "Parque de la Vida, Armenia",
            description: "Degustación de café, charlas sobre cultivo, tiendas de café gourmet y más.",
            price: 48000,
            image: "images/café.jpg",
            featured: true
        },
        {
            id: 1402,
            name: "Concierto Música Del Eje Cafetero",
            category: "musica",
            date: "17 Feb 2026",
            time: "19:30 - 22:00",
            location: "Teatro Bolívar, Armenia",
            description: "Artistas de la región cafetera en concierto de música folclórica y popular.",
            price: 45000,
            image: "images/música.jpg",
            featured: false
        },
        {
            id: 1403,
            name: "Tour Finca Cafetera Sostenible",
            category: "negocios",
            date: "21 Feb 2026",
            time: "08:00 - 15:00",
            location: "Finca Cafetera, Armenia",
            description: "Visita a finca con cultivo sostenible de café de especialidad. Desayuno incluido.",
            price: 95000,
            image: "images/café.jpg",
            featured: true
        },
        {
            id: 1404,
            name: "Exposición Arte y Fotografía",
            category: "cultura",
            date: "01 Mar 2026",
            time: "10:00 - 18:00",
            location: "Galería de Arte, Armenia",
            description: "Obras de artistas locales y fotógrafos de la región cafetera.",
            price: 20000,
            image: "images/fotografia.jpg",
            featured: false
        },
        {
            id: 1405,
            name: "Maratón Cafetero Armenia",
            category: "deportes",
            date: "06 Mar 2026",
            time: "06:00 - 11:00",
            location: "Centro de Armenia, Armenia",
            description: "Carrera de 10 km por las calles de Armenia. Salida y llegada en zona cafetera.",
            price: 45000,
            image: "images/atletismo.jpg",
            featured: false
        },
        {
            id: 1406,
            name: "Seminario Innovación Agrícola",
            category: "tecnologia",
            date: "11 Mar 2026",
            time: "08:00 - 16:00",
            location: "Universidad Tecnológica del Quindío, Armenia",
            description: "Innovaciones tecnológicas en producción cafetera y agricultura sostenible.",
            price: 0,
            image: "images/tecnologia.jpg",
            featured: false
        },
        {
            id: 1407,
            name: "Festival Gastronómico Quindiano",
            category: "gastronomia",
            date: "15 Mar 2026",
            time: "12:00 - 20:00",
            location: "Centro Comercial, Armenia",
            description: "Platos típicos del Eje Cafetero: bandeja paisa, ajiaco, empanadas y arepas.",
            price: 55000,
            image: "images/gastronomia.jpg",
            featured: false
        }
    ]
};

// Función para obtener eventos por ciudad
function getEventsByCity(cityId) {
    return eventsData[cityId] || [];
}

// Función para obtener todos los eventos
function getAllEvents() {
    let allEvents = [];
    Object.values(eventsData).forEach(cityEvents => {
        allEvents = allEvents.concat(cityEvents);
    });
    return allEvents;
}
